import os
import io
from typing import List, Dict
import polars as pl
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from groq import Groq
from dotenv import load_dotenv
import uvicorn

# Load environment variables
load_dotenv()

app = FastAPI(title="Dataswiss Pro Engine", version="3.1.0")
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- GATHERING: MULTI-FORMAT UPLOADS ---
@app.post("/api/upload")
async def upload_file(file: UploadFile = File(...)):
    contents = await file.read()
    filename = file.filename.lower()
    
    try:
        if filename.endswith('.csv'):
            df = pl.read_csv(io.BytesIO(contents))
        elif filename.endswith('.json'):
            df = pl.read_json(io.BytesIO(contents))
        elif filename.endswith(('.xlsx', '.xls')):
            # Fast Excel engine
            df = pl.read_excel(io.BytesIO(contents), engine="calamine")
        else:
            raise HTTPException(status_code=400, detail="Unsupported format. Use CSV, JSON, or Excel.")
        
        # Drop rows that are entirely null (common in Excel exports)
        df = df.filter(~pl.all_horizontal(pl.all().is_null()))
        
        return {"data": df.to_dicts()}
    except Exception as e:
        print(f"Upload Error: {e}")
        raise HTTPException(status_code=500, detail=f"Engine Error: {str(e)}")

# --- TRANSFORMATION: POLARS REFINEMENT ---
@app.post("/api/transform")
async def transform_data(payload: List[Dict]):
    try:
        df = pl.DataFrame(payload)
        cols = df.columns
        
        # Identify column types dynamically
        str_cols = [c for c in cols if df[c].dtype == pl.String]
        num_cols = [c for c in cols if df[c].dtype in [pl.Int64, pl.Float64]]
        
        operations = [pl.lit("refined").alias("status")]
        
        # Capitalize all string columns
        for c in str_cols:
            operations.append(pl.col(c).str.to_titlecase())
            
        # Scale all numeric columns by 1.2 (Optimization simulation)
        for c in num_cols:
            operations.append((pl.col(c) * 1.2).alias(c))

        refined_df = df.with_columns(operations)
        return {"data": refined_df.to_dicts()}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Transformation failed: {e}")

# --- INTELLIGENCE: GROQ AI ---
@app.post("/api/ai-insight")
async def get_ai_insight(payload: List[Dict]):
    try:
        # Pass a representative sample to the AI
        summary = str(payload[:15])
        completion = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": "You are an Elite Data Scientist. Analyze the data and provide 2 punchy, professional sentences of insight."},
                {"role": "user", "content": f"Analyze these records: {summary}"}
            ]
        )
        return {"insight": completion.choices[0].message.content}
    except Exception as e:
        print(f"Groq API Error: {e}")
        return {"insight": "AI could not reach the brain. Verify the GROQ_API_KEY in your .env file."}

# --- REPORTING: MARKDOWN EXPORT ---
@app.post("/api/export")
async def export_report(payload: List[Dict]):
    try:
        df = pl.DataFrame(payload)
        # Using pandas/tabulate via Polars for clean MD formatting
        md_table = df.to_pandas().to_markdown(index=False)
        report = f"# Dataswiss Intelligence Report\n\n## Refined Dataset\n{md_table}\n\n---\n*Generated by Dataswiss Pro Engine*"
        return Response(content=report, media_type="text/markdown")
    except Exception as e:
        raise HTTPException(status_code=500, detail="Export failed.")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)